#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$command = $argv[1] ?? null;
$subcommand = $argv[2] ?? null;

switch ($command) {
    case 'run':
        $host = 'localhost';
        $port = '8300';
        echo "Artemis berjalan di http://$host:$port\n";
        shell_exec("php -S $host:$port -t public/");
        break;

    default:
        echo "Perintah tidak ditemukan: $command\n";
        echo "Gunakan: php artemis run\n";
}